In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
df = pd.read_csv('weatherAUS.csv')
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [2]:
df["MinTemp"].fillna(value=np.mean(df["MinTemp"]),inplace=True)
df["MaxTemp"].fillna(value=np.mean(df["MaxTemp"]),inplace=True)
df["Rainfall"].fillna(value=np.mean(df["Rainfall"]),inplace=True)
#df["WindGustDir"].fillna(value=np.mean(df["WindGustDir"]),inplace=True)
df["WindGustSpeed"].fillna(value=np.mean(df["WindGustSpeed"]),inplace=True)
#df["WindDir9am"].fillna(value=np.mean(df["WindDir9am"]),inplace=True)
#df["WindDir3pm"].fillna(value=np.mean(df["WindDir3pm"]),inplace=True)
df["WindSpeed9am"].fillna(value=np.mean(df["WindSpeed9am"]),inplace=True)
df["WindSpeed3pm"].fillna(value=np.mean(df["WindSpeed3pm"]),inplace=True)
df["Humidity9am"].fillna(value=np.mean(df["Humidity9am"]),inplace=True)
df["Humidity3pm"].fillna(value=np.mean(df["Humidity3pm"]),inplace=True)
df["Pressure9am"].fillna(value=np.mean(df["Pressure9am"]),inplace=True)
df["Pressure3pm"].fillna(value=np.mean(df["Pressure3pm"]),inplace=True)
df["Temp9am"].fillna(value=np.mean(df["Temp9am"]),inplace=True)
df["Temp3pm"].fillna(value=np.mean(df["Temp3pm"]),inplace=True)

In [3]:
df.drop("Evaporation",axis=1, inplace=True)
df.drop("Sunshine",axis=1, inplace=True)
df.drop("WindGustDir",axis=1, inplace=True)
df.drop("WindDir9am",axis=1, inplace=True)
df.drop("WindDir3pm",axis=1, inplace=True)
df.drop("Cloud9am",axis=1, inplace=True)
df.drop("Cloud3pm",axis=1, inplace=True)

In [4]:
def converter(x):
    if(x=="Yes"):
        return 1
    else:
        return 0
    
df["RTom"]=df["RainTomorrow"].apply(converter)
df["RTod"]=df["RainToday"].apply(converter)

In [5]:
data = df.drop(["Date","Location","RainToday","RainTomorrow"],axis=1)

In [6]:
data.head()

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0     13.4     22.9       0.6           44.0          20.0          24.0   
1      7.4     25.1       0.0           44.0           4.0          22.0   
2     12.9     25.7       0.0           46.0          19.0          26.0   
3      9.2     28.0       0.0           24.0          11.0           9.0   
4     17.5     32.3       1.0           41.0           7.0          20.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Temp9am  Temp3pm  RTom  \
0         71.0         22.0       1007.7       1007.1     16.9     21.8     0   
1         44.0         25.0       1010.6       1007.8     17.2     24.3     0   
2         38.0         30.0       1007.6       1008.7     21.0     23.2     0   
3         45.0         16.0       1017.6       1012.8     18.1     26.5     0   
4         82.0         33.0       1010.8       1006.0     17.8     29.7     0   

   RTod  
0     0  
1     0  
2     0  
3     0  
4     0

In [7]:
from sklearn.model_selection import train_test_split
X=data.drop("RTom",axis=1)
y=data["RTom"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [ ]:
#RANDOM FOREST

In [11]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=77)
rfc.fit(X_train,y_train)
rfc_pred=rfc.predict(X_test)

In [9]:


from sklearn.metrics import classification_report,confusion_matrix



print(confusion_matrix(y_test,rfc_pred))
print("\n")
print(classification_report(y_test,rfc_pred))



[[32312  1746]
 [ 4869  4711]]


              precision    recall  f1-score   support

           0       0.87      0.95      0.91     34058
           1       0.73      0.49      0.59      9580

    accuracy                           0.85     43638
   macro avg       0.80      0.72      0.75     43638
weighted avg       0.84      0.85      0.84     43638



In [12]:
from sklearn.metrics import classification_report,confusion_matrix



print(confusion_matrix(y_test,rfc_pred))
print("\n")
print(classification_report(y_test,rfc_pred))



[[32334  1724]
 [ 4835  4745]]


              precision    recall  f1-score   support

           0       0.87      0.95      0.91     34058
           1       0.73      0.50      0.59      9580

    accuracy                           0.85     43638
   macro avg       0.80      0.72      0.75     43638
weighted avg       0.84      0.85      0.84     43638



In [ ]:
#TREE

In [13]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix
pred = dtree.predict(X_test)
print(classification_report(y_test,pred))
print("\n")
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      0.85      0.86     34058
           1       0.49      0.52      0.51      9580

    accuracy                           0.78     43638
   macro avg       0.68      0.69      0.68     43638
weighted avg       0.78      0.78      0.78     43638



[[28873  5185]
 [ 4554  5026]]
